0xIntuition/intuition-ts

packages/graphql/src/fragments/account.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/accounts.graphql
Apps
Packages
Tools
- Note: This PR is into the `feature/graphql-migration` branch, not `main`
- Updates our `account.graphql` fragments and `accounts.graphql` queries (`GetAccount` and `GetAccounts`) to include the `createdAtoms_aggregate` and `createdTriples_aggregate` and supporting variables
- This is a response to @Vitalsine85 and I exploring the queries that we'd need for each specific page in Portal and we needed to add these to the query to match the use cases.
=> ENG-4672 feat(graphql): update account queries

apps/portal/app/.client/providers.tsx
Apps
Packages
Tools
- Adds in the HydrationBoundary in the providers.tsx -- this enables the partial hydration pattern referenced in https://github.com/0xIntuition/intuition-ts/pull/885
- Once this wraps Portal via the providers we can partially hydrate as long as the queryKey matches server + client side. This won't have any bearing on our client-side only hooks such as in modals but enables the hydration pattern where loaders are available
- The HydrationBoundary ensures that our client-side cache for each query (where loaders are available) starts with the same data that was fetched and rendered on the server
- Note: This re-opens PR #888 into `feature/graphql-migration` instead of onto `main`
=> ENG-4659 feat(portal): set up hydration boundary

apps/portal/app/components/follow/follow-button.tsx, apps/portal/app/components/follow/follow-form.tsx, apps/portal/app/components/follow/follow-modal.tsx, apps/portal/app/components/follow/unfollow-button.tsx, apps/portal/app/components/home/home-stats-header.tsx, apps/portal/app/lib/hooks/mutations/useFollowMutation.tsx, apps/portal/app/lib/hooks/mutations/useStakeMutation.tsx
Apps
Packages
Tools
- Added useFollowMutation hook which handles the transaction and updating queries based on their queryKeys.
- Removed fetchReval fetcher in favor of this new method.
- Renamed GetStats query key to get-stats to follow standard.
=> ENG-4667 feat(portal): replace fetchers with react query hooks in follow modal

apps/portal/app/routes/actions+/clear-onboarding-cookie.tsx, apps/portal/app/routes/login.tsx
Apps
Packages
Tools
Added a back button the header on the login route which navigates to the big bang (carousel) so that users can revisit that experience.
=> ENG-4314 feat(portal): add back button to login header

apps/data-populator/app/components/csv-uploader.tsx, apps/data-populator/app/components/header.tsx, apps/data-populator/app/components/ui/tabs.tsx, apps/data-populator/app/lib/utils/tooltips.ts, apps/data-populator/app/routes/app+/index.tsx, apps/data-populator/package.json, packages/1ui/src/components/Table/Table.spec.tsx, packages/1ui/src/components/Table/Table.tsx, pnpm-lock.yaml
Apps
Packages
Tools
This PR low-lift polishes up main page of data-populator.  It includes a refactor of tabs so all user forms are encapsulated into a tab card, separated from the table so it can always be editted, updated.
I refrained from updating any business logic.  The only business logic change is how loadCSV is triggered when a new CSV is uploaded.
* Refactor tabs
* Restructure & polish UI
=> ENG-0000 feat(repo): Update data-populator main page UI

apps/portal/app/components/follow/follow-modal.tsx, render.yaml
Apps
Packages
Tools
- This updates the `render.yaml` file to deploy a GraphQL version of Portal for QA during the migration
- This is only temporary -- since this'll live only on that feature branch we'll want to create a unified `render.yaml` for this and Data Populator when we merge back into `main` -- we'd likely want to completely remove the GraphQL Render deployment at that point. We'll revert the `render.yaml` back to the Data Populator version (or unify the two if we want to go that route for future deployments)
- I tested the deployment from this branch and it works -- once we merge this in to the `feature/graphql-migration` branch I can update the deployment target to that branch for ongoing QA
=> ENG-4677 feat(repo): graphql render deployment for qa

apps/portal/app/components/create-identity/create-identity-form.tsx
Apps
Packages
Tools
Fixed an issue where vault_id was being passed as null into the completion screen when creating an identity which was causing the 'View Identity' button to navigate to a bad route.
=> ENG-4447 fix(portal): fix vault_id is null after identity creation

packages/1ui/src/components/ProfileCard/ProfileCard.tsx
Apps
Packages
Tools
Increased the maxLength in the ProfileCard component to match the max chars now allowed in an identities description. When it was < the max chars, it was creating some weird styling issues.
=> ENG-4696 fix(portal): increase maxLength on Trunctacular in ProfileCard

packages/graphql/src/fragments/account.graphql, packages/graphql/src/fragments/atom.graphql, packages/graphql/src/fragments/deposit.graphql, packages/graphql/src/fragments/event.graphql, packages/graphql/src/fragments/redemption.graphql, packages/graphql/src/fragments/triple.graphql, packages/graphql/src/fragments/vault.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/atoms.graphql, packages/graphql/src/queries/events.graphql
Apps
Packages
Tools
- Adds metadata to several queries (this is an iteration -- may still need refinement)
- Rounds out the `GetEvents` query to support the use cases we need for Portal as well as allowing for filtering by multiple addresses on the positions on the activity/event feed
- Updates all of the related fragments to support all of these use cases
- Runs codegen to generate updated queries and hooks
- Note: May still need additional tweaks -- will either do a separate small PR or as part of the specific feature it's being used in
=> ENG-4690 feat(graphql): update queries include metadata and refine events query

apps/portal/app/components/list/activity.tsx, apps/portal/app/components/stake/stake-form.tsx, packages/1ui/src/components/ClaimRow/ClaimRow.spec.tsx, packages/1ui/src/components/ClaimRow/ClaimRow.tsx, packages/1ui/src/components/IdentityRow/IdentityRow.spec.tsx, packages/1ui/src/components/IdentityRow/IdentityRow.tsx, packages/1ui/src/components/StakeButton/StakeButton.tsx
Apps
Packages
Tools
- Improved the gradient and color on ClaimRow and IdentityRow for better visibility
- Improved visibility of StakeButton on IdentityRow when a user has a position
- Improved the gradient on the TabList in StakeForm
=> ENG-4704 fix(portal,1ui): refine gradients in claim and identity row

apps/portal/app/components/list/activity.tsx, apps/portal/app/components/list/claims.tsx, apps/portal/app/components/list/list-claims.tsx, apps/portal/app/components/lists/featured-lists-carousel.tsx, apps/portal/app/components/lists/list-skeletons.tsx, apps/portal/app/components/stake/stake-modal.tsx, apps/portal/app/routes/app+/claim+/$id.tsx, apps/portal/app/routes/app+/explore+/_index+/lists.tsx, apps/portal/app/routes/app+/home.tsx, apps/portal/app/routes/app+/identity+/$id.tsx, apps/portal/app/routes/app+/profile+/$wallet.tsx, apps/portal/app/routes/app+/profile+/_index+/_layout.tsx, apps/portal/app/routes/app+/profile+/_index+/index.tsx, apps/portal/app/routes/login.tsx, packages/1ui/src/components/Button/Button.tsx, packages/1ui/src/components/Claim/Claim.spec.tsx, packages/1ui/src/components/Claim/Claim.tsx, packages/1ui/src/components/ClaimRow/ClaimRow.spec.tsx, packages/1ui/src/components/ClaimRow/ClaimRow.tsx, packages/1ui/src/components/ClaimStatus/ClaimStatus.spec.tsx, packages/1ui/src/components/FeaturedListCard/FeaturedListCard.spec.tsx, packages/1ui/src/components/FeaturedListCard/FeaturedListCard.tsx, packages/1ui/src/components/IdentityRow/IdentityRow.spec.tsx, packages/1ui/src/components/IdentityRow/IdentityRow.tsx, packages/1ui/src/components/ListGrid/ListGrid.spec.tsx, packages/1ui/src/components/ListGrid/ListGrid.tsx, packages/1ui/src/components/ListHeaderCard/ListHeaderCard.spec.tsx, packages/1ui/src/components/StakeButton/StakeButton.tsx, packages/1ui/src/components/StakeTVL/StakeTVL.spec.tsx, packages/1ui/src/components/StakeTVL/StakeTVL.tsx
Apps
Packages
Tools
Fixed some issues with responsiveness/mobile, primarily surround the new Claim/Identity/ActivityRow, ListCard, ListGrid, and FeaturedListsCarousel. There are some other tweaks here and there, but nothing notable.
=> ENG-4712 fix(portal,1ui): responsiveness fixes

apps/portal/app/components/list/tags.tsx, apps/portal/app/components/lists/featured-lists-carousel.tsx, packages/1ui/src/components/IdentityRow/IdentityRow.tsx
Apps
Packages
Tools
** This was branched off of `vital/eng-4712-responsiveness-fixes`. Make sure that gets merged in first, and rebase this off main before merging** 
Removes the staking buttons and context menu from IdentityRow on List Detail route. Staking was removed because it doesn't make sense in this context, you'd be staking on the subject identity of the has tag claim, and we already have the save list functionality baked into this. Removed the context button because it lives inside of IdentityRow and clashes with the save list button. Should revisit when we get to the list and detail page rework and create a specific row component for list details.
=> ENG-4713 fix(portal,1ui): remove staking from identity rows on list detail

packages/graphql/src/generated/index.ts, packages/graphql/src/queries/accounts.graphql, packages/graphql/src/queries/atoms.graphql, packages/graphql/src/queries/claims.graphql, packages/graphql/src/queries/events.graphql, packages/graphql/src/queries/lists.graphql, packages/graphql/src/queries/positions.graphql, packages/graphql/src/queries/triples.graphql, packages/graphql/src/queries/vaults.graphql
Apps
Packages
Tools
- Adds `aggregate` `count` field to all queries that use the `_aggregate` field so we can have an accurate count for pagination.
- Re-runs codegen to add this to queries and hooks.
=> ENG-4720 feat(graphql): add aggregate counts to aggregate queries

apps/portal/app/routes/app+/list+/$id+/index.tsx, apps/portal/app/routes/readonly+/list+/$id+/index.tsx
Apps
Packages
Tools
When visiting List Details, if the username for the additional tab was > 12 characters it was causing the text to overflow out of the tab.
=> ENG-4718 fix(portal): truncate text in the additional tab on list details route

apps/portal/app/components/profile/overview-about-header.tsx, apps/portal/app/components/profile/overview-created-header.tsx, apps/portal/app/components/profile/overview-staking-header.tsx
Apps
Packages
Tools
Formats long numbers in Profile Overview cards as well as reduces the number of decimals shown for TVL in those cards to 2 to prevent overflow issues.
=> ENG-4732 fix(portal): format numbers on profile overview cards

packages/1ui/src/components/StakeButton/StakeButton.tsx, packages/1ui/src/utils/number.spec.ts, packages/1ui/src/utils/number.ts
Apps
Packages
Tools
Formats large numbers down to prevent issues with icon shrinking/overflow in StakeButtons. i.e. 2,330 -> 2.3k 
=> ENG-4730 fix(1ui): format large numbers in StakeButton

apps/template/app/routes/app+/playground-hydration-search.tsx, apps/template/app/routes/app+/playground-hydration.tsx, apps/template/app/routes/app+/playground.tsx, packages/graphql/src/fragments/account.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/accounts.graphql, packages/graphql/src/queries/atoms.graphql, packages/graphql/src/queries/events.graphql, packages/graphql/src/queries/positions.graphql, packages/graphql/src/queries/triples.graphql
Apps
Packages
Tools
- Updates core queries and fragments to use a split approach that's more aligned with Hasura best practices for aggregates and data querying for use in pagination. 
- Adds Get[Entities]WithAggregate queries and Get[Entities]Count queries for more flexibility and thoroughness for the exported queries/hooks from our package
- Runs codegen with the new queries
- Updates the template playground routes that use this
- Note: We'll likely need to keep tweaking these -- covering as many bases as we need and updating as we implement in specific use cases
=> ENG-4741 feat(graphql,template): refine aggregate queries pagination and update template playground

apps/template/app/routes/app+/playground.tsx, packages/graphql/src/fragments/position.graphql, packages/graphql/src/fragments/triple.graphql, packages/graphql/src/fragments/vault.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/tags.graphql
Apps
Packages
Tools
- Adds in `GetTags` and `GetTagsCustom` queries in `tags.graphql` -- `GetTags` is more streamlined and specific with the variables it takes (`subjectId` and `predicateId`) whereas `GetTagsCustom` uses a more general `where` for the variable. This allows for more flexible use, whereas the `GetTags` covers almost all of our tag related use cases
- Updates the fragments to support the data we need in these queries
- Runs codegen and updates the template to remove `triple.label` from use since it's removed from the `TripleMetadata` fragment
=> ENG-4478 feat(graphql,template): query consumer tags, codegen, minor template update

apps/portal/app/components/create-identity/create-caip10-account-form.tsx
Apps
Packages
Tools
- Uses getAddress from Viem to validate the address users input in caip10 atom creation.
=> ENG-4757 feat(portal): validate address with getAddress in caip10 creation flow

apps/portal/app/components/stake/stake-review.tsx
Apps
Packages
Tools
ScrollArea on staking review screens was overflowing on wider screens < 800px in height. This is a temporary fix for that. We can revisit this when we get back to working on modal standardization.
=> ENG-4780 fix(portal): make scrollarea height more responsive in review staking screens

packages/graphql/src/fragments/atom.graphql, packages/graphql/src/generated/index.ts
Apps
Packages
Tools
- Adds `data` to the `AtomMetadata` fragment 
- Re-runs codegen
=> ENG-0000 feat(graphql): add data atom metadata fragment

apps/portal/app/routes/app.tsx
Apps
Packages
Tools
- Adds logic to app.tsx to clear old domain `privy-session` cookie
=> ENG-0000 fix(portal): adds logic to app.tsx to clear old domain privy-session

apps/portal/app/.server/privy.ts, apps/portal/app/routes/app.tsx
Apps
Packages
Tools
- Updates the cookie check logic to `httpOnly` to `false`
- Wraps the `verifyPrivyAccessToken` in a try/catch block
=> ENG-0000 fix(portal): changes httpOnly logic to false and wraps verifyPrivyAccessToken

apps/portal/app/routes/resources+/get-claim.tsx
Apps
Packages
Tools
- Increases max retries from 1 to 10 in the get claim resource route.
=> ENG-4803 fix(portal): increase retries to 10 in get claim resource route

apps/portal/app/components/edit-profile/modal.tsx, apps/portal/app/components/tags/add-tags.tsx, apps/portal/app/components/tags/tags-form.tsx, apps/portal/app/components/tags/tags-modal.tsx, apps/portal/app/components/tags/tags-search-combo-box.tsx, apps/portal/app/routes/app+/profile+/_index+/_layout.tsx, packages/1ui/src/components/ProfileCard/ProfileCard.tsx, packages/1ui/src/components/ProfileCard/components/ProfileCardStatItem.tsx, packages/graphql/src/fragments/account.graphql, packages/graphql/src/fragments/atom.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/accounts.graphql, packages/graphql/src/queries/follows.graphql
Apps
Packages
Tools
- Updates queries and fragments to support what we need for the user metadata. Runs codegen
- Uses the `useGetVaultDetails` hook and GraphQL hooks for all user data (excluding Points)
- This includes several TODO comments flagging our need to fix/update the type safety once we lock it all in
- This breaks the  _View All Tags_ modal but there are a lot of other pieces we need to fix to get this to work and we'll need to revisit it
=> ENG-4769 feat(portal,graphql): user profile metadata left panel

apps/portal/app/components/create-claim/create-claim-form.tsx, apps/portal/app/components/follow/follow-button.tsx, apps/portal/app/components/follow/follow-form.tsx, apps/portal/app/components/follow/follow-modal.tsx, apps/portal/app/components/follow/follow-review.tsx, apps/portal/app/lib/hooks/mutations/useFollowMutation.tsx, apps/portal/app/routes/app+/profile+/$wallet.tsx
Apps
Packages
Tools
- Now fetches the vaultDetails, followClaim, etc inside of the follow modal rather than passing it in from route
=> ENG-4832 feat(portal): use graphql queries within follow modal

apps/portal/app/components/list/claims.tsx, apps/portal/app/components/list/positions-on-identity.tsx, apps/portal/app/components/profile/data-about-header.tsx, apps/portal/app/routes/app+/identity+/$id+/index.tsx, apps/portal/app/routes/app+/identity+/$id.tsx, package.json, packages/graphql/src/fragments/position.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/positions.graphql, packages/graphql/src/queries/triples.graphql
Apps
Packages
Tools
- Converts all of Identity Details to use GraphQL API
- Updates several components to work with this, including pagination, but keeps the previous version until we fully migrate to keep the typechecks building
- Note: Still need pagination/sort/search adjustments but those are in another ticket. We also need to tweak the staking actions, but we're going to do that in a separate PR.
=> ENG-4471 feat(portal,graphql): query consumer identity details

apps/portal/app/routes/app+/identity+/$id+/index.tsx, apps/portal/app/routes/app+/profile+/_index+/_layout.tsx, apps/portal/app/routes/app+/profile+/_index+/data-about.tsx, packages/graphql/src/queries/triples.graphql
Apps
Packages
Tools
- Builds out the user profile data about route and switches to use new versions of the list components
- Pagination/search/sort still WIP but the rest of the data is loading using GraphQL now
- All fields / metadata working as expected except for the TVL on the triples query -- there is a TODO with a note about this in the code comments
=> ENG-4765 feat(portal): user profile data about change to use graphql

apps/portal/app/components/profile/image-modal.tsx, apps/portal/app/routes/app+/identity+/$id.tsx, apps/portal/app/routes/app+/list+/$id.tsx, apps/portal/app/routes/app+/profile+/$wallet.tsx, apps/portal/app/routes/app+/profile+/_index+/_layout.tsx, apps/portal/app/routes/readonly+/identity+/$id.tsx, apps/portal/app/routes/readonly+/list+/$id.tsx, apps/portal/app/routes/readonly+/profile+/$wallet.tsx
Apps
Packages
Tools
Updates ImageModal to handle the props individually rather than passing the full atom object. While we may want to simplify this by passing the complete atom in the future, the current type mismatches between the GraphQL and legacy API make granular prop handling more maintainable.
=> ENG-4831 fix(portal): update image modal component to use graphql

apps/portal/app/components/detail-info-card.tsx, apps/portal/app/components/list/positions-on-claim.tsx, apps/portal/app/routes/app+/claim+/$id+/index.tsx, apps/portal/app/routes/app+/claim+/$id.tsx, packages/graphql/src/fragments/triple.graphql, packages/graphql/src/generated/index.ts
Apps
Packages
Tools
- Converts the Claim Details pages (index and id) to use GraphQL. Adds the necessary queries to get the data as well as check if the Claim is part of a List and also to pull the For/Against positions. Creates a new version of the DetailInfoCard component to not break the Readonly route build until we fully migrate and then we can remove
- Handling the positions was the biggest change from the previous implementation. Previously, all positions came through in a single list with a `for` and `against` direction as a property. This isn't the case now, so we needed to combine the vault and counterVault positions together. This works, but there are definitely performance improvements, especially since we should likely be doing the tab filtering client side instead of a …
=> ENG-4472 feat(portal,graphql): query consumer claim details

apps/portal/app/lib/hooks/mutations/useStakeMutation.tsx, apps/portal/app/routes/app+/claim+/$id+/index.tsx
Apps
Packages
Tools
- Added better handling for invalidating queries on stake actions
=> ENG-4886 feat(portal): handle invalidateQueries better on stake action

apps/template/app/routes/app+/playground.tsx, packages/graphql/package.json, packages/graphql/src/client.ts, packages/graphql/src/fragments/account.graphql, packages/graphql/src/fragments/atom.graphql, packages/graphql/src/fragments/deposit.graphql, packages/graphql/src/fragments/event.graphql, packages/graphql/src/fragments/follow.graphql, packages/graphql/src/fragments/position.graphql, packages/graphql/src/fragments/redemption.graphql, packages/graphql/src/fragments/triple.graphql, packages/graphql/src/fragments/vault.graphql, packages/graphql/src/generated/index.ts, packages/graphql/src/queries/accounts.graphql, packages/graphql/src/queries/atoms.graphql, packages/graphql/src/queries/claims.graphql, packages/graphql/src/queries/events.graphql, packages/graphql/src/queries/lists.graphql, packages/graphql/src/queries/positions.graphql, packages/graphql/src/queries/triples.graphql, packages/graphql/src/queries/vaults.graphql
Apps
Packages
Tools
- This PR pulls in our updates to our GraphQL package that we made while dogfooding the `feature/graphql-migration` work. We've decided to decouple the package updates from the migration so that we can publish the most updated package (as of the time of this PR). 
- Decoupling in this way allows for us to keep working on the migration while unblocking building/consumption of the package by external/internal app consumers.
- Updates and adds new fragments and queries, runs codegen, and manually bumps version due to all of the changes and additions.
- Also had to update the `playground.tsx` route in `template` to work with the newly updated hooks as part of this PR.
=> ENG-4934 feat(graphql,template): graphql package updates from feature branch

apps/template/app/root.tsx, packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/src/client.ts, packages/graphql/src/constants.ts, packages/graphql/src/index.ts
Apps
Packages
Tools
- Adds support for a configurable `apiUrl` for the GraphQL package. A `configureClient` is now exported along with API URLs as constants. Consuming apps can optionally call `configureClient` at the highest level of their app (such as `root.tsx` in Remix, `layout.tsx` in Next.js app router, or above the app configuration in an Express app). 
- The `DEFAULT_API_URL` in the package is currently set to dev for now.
- This uses a similar configuration approach to Prisma and Apollo, such as: `configureClient({
apiUrl: process.env.NODE_ENV === 'production' ? API_URL_PROD : API_URL_DEV,
})` which has been added to the template's `root.tsx` as an example.
- Note: If you're running Hasura locally you'll need to change the port that the template/Portal runs on.
- Bumps the …
=> ENG-4592 feat(graphql,template): add environment handling graphql and example in template

.gitignore, .prettierignore, .verdaccio/config.yml, packages/1ui/project.json, packages/1ui/tsconfig.json, packages/1ui/tsconfig.typecheck.json, packages/1ui/types.d.ts, packages/graphql/README.md, packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/project.json, packages/graphql/src/client.ts, packages/graphql/src/constants.ts, packages/graphql/src/index.ts, packages/graphql/tsconfig.json, packages/graphql/tsup.config.ts, pnpm-lock.yaml, tsconfig.base.json
Apps
Packages
Tools
- Brings in crucial parts of the most recent PRs into `main` so that we can continue working on migrating to the new schema/architecture on the `feature/graphql-migration` branch
- This includes the logic in #969 -- we'll want to review that first so any changes can also be reflected in here. Including that logic will make working with the local API/schema more direct since we can configure the URL a bit easier.
- I'm reasonably sure that I got everything. We'll have to deal with this again when we merge this branch into `main` but now that the GraphQL package is published #969 should be the last PR until we merge this feature branch in. If we change approaches we can modify the feature branch accordingly
If applicable, add screenshots or screen captures of your …
=> ENG-4995 feat(1ui,graphql): update feature branch main

apps/portal/app/components/list/claims.tsx, apps/portal/app/routes/readonly+/identity+/$id+/index.tsx, apps/portal/app/routes/readonly+/identity+/$id.tsx
Apps
Packages
Tools
Updates the read only identity detail route to use GraphQL.
NOTE: Marking as Do Not Merge until i7n issues are resolved and we can properly test.
=> ENG-4942 feat(portal): convert identity read only route to use graphql

apps/portal/app/components/detail-info-card.tsx, apps/portal/app/routes/readonly+/claim+/$id+/index.tsx, apps/portal/app/routes/readonly+/claim+/$id.tsx
Apps
Packages
Tools
Updates the read only claim detail route to use GraphQL.
NOTE: Marking as Do Not Merge until i7n issues are resolved and we can properly test.
=> ENG-4941 feat(portal): convert claim read only route to use graphql

apps/data-populator/app/lib/services/attestor.ts, apps/data-populator/app/lib/services/offchain-store.ts, apps/data-populator/app/lib/services/populate.ts, apps/data-populator/app/lib/services/supabase.ts, apps/data-populator/app/routes/app+/index.tsx
There were:
Issues in how the database was remembering Atom IDs and their associated URIs
This was consistently failing and falling back on batch EVM reads
Issues in how an existing atom was being checked when its info was edited
The Type was not being provided, so edited atoms were checked as if their full metadata was just  { https://schema.org/ }
Issues in how the database was being polled or written with large batches of data (like a CSV full of atom data or their image src urls)
Batches were chunked into requests of 100, without accounting for the length of each item - causing header overflow
This took a couple hours to resolve and track down as I was testing very thoroughly and tracing all the internal steps.  But good thing we fixed this.  This will:
Enhance stability and …
=> ENG-5006 fix(data-populator): atom existence bugs and db optimizations

apps/data-populator/app/components/header.tsx, apps/data-populator/app/root.tsx, apps/data-populator/app/routes/app+/index.tsx
Fixed these:
https://linear.app/0xintuition/issue/ENG-4892/[data-populator]-not-sure-if-tag-was-actually-created-not-sure-what-to
https://linear.app/0xintuition/issue/ENG-4890/[data-populator]-no-handling-of-additional-table-columns
https://linear.app/0xintuition/issue/ENG-4898/[data-populator]-add-a-beta-flag-so-that-people-understand-this-is
https://linear.app/0xintuition/issue/ENG-4895/[data-populator]-pre-select-all-of-the-uploaded-atoms-for-publishing
https://linear.app/0xintuition/issue/ENG-4894/[data-populator]-cant-close-toast-messages
https://linear.app/0xintuition/issue/ENG-4799/[data-populator]-notify-user-is-bunk-header-is-loaded-in-csv
Summary:
- Loading a CSV causes all the atom rows to be auto-selected
- Headers and columns are parsed and compared against expected default. …
=> ENG-4898 feat(data-populator): Fix CSV header proofreading, update app header, fix toast, add title

apps/launchpad/app/components/ActivityFeed.tsx, apps/launchpad/app/consts/general.ts, apps/launchpad/app/routes/network.tsx, apps/launchpad/package.json, packages/1ui/src/components/Avatar/Avatar.tsx, packages/1ui/src/components/IdentityTag/IdentityTag.tsx, packages/1ui/src/components/NetworkStats/NetworkStats.spec.tsx, packages/1ui/src/components/PageHeader/PageHeader.stories.tsx, packages/1ui/src/components/Sidebar/Sidebar.spec.tsx, pnpm-lock.yaml
Apps
Packages
Tools
Initially started building this in 1ui but then came to the conclusion that it is tied too heavily into our logic for this to be a fit. Moved into the launchpad and got it up on the Network route. Definitely needs some more love and will have to work out some of the data with BE once they're deployed.
=> ENG-5171 feat(launchpad,1ui): create activity feed and add to network route

packages/graphql/codegen.ts
Apps
Packages
Tools
- Removes the fallback for localhost -- uses the dev API URL instead.
=> ENG-0000 fix(repo): removes the localhost fallback for codegen

apps/launchpad/app/routes/preferences+/item+/$itemId.tsx
Apps
Packages
Tools
- Scaffolds the atom details route in Launchpad -- this can be viewed for testing the UX in the `/preferences` route and by selecting a single item (not a folder) in the sidebar
- Builds out the UI from the Figma with placeholder data for now, but this will come in from the actual atom once we wire up the query
- Uses the dynamic placeholder data and dynamic routes
=> ENG-5229 feat(repo): scaffold atom details in launchpad

packages/graphql/package.json
Apps
Packages
Tools
- Sets version to `0.3.0` from `0.4.0` in the GraphQL package -- accidentally skipped a version since pulling in from feature branch.
=> ENG-0000 fix(graphql): corrects the version to 0.3.0 from 0.4.0

packages/graphql/package.json, packages/sdk/package.json, packages/sdk/src/index.ts, pnpm-lock.yaml
Apps
Packages
Tools
- Removes the inclusion of the `0xintuition/api` package as dependency in `graphql` and `sdk` packages
- Ran a `pnpm install` afterward so the `pnpm-lock.yaml` change reflects this
- This resolves installation issues for apps outside of the monorepo
- Note: Leaving it in the `template` and `data-populator` for now because it's more integrated as part of certain flows. We can remove these gradually -- don't want to disrupt any working flows at the moment.
=> ENG-5279 feat(graphql,sdk): remove api dependencies from sdk and graphql

apps/launchpad/app/components/KnowledgeGraph/KnowledgeGraph.tsx, apps/launchpad/vite.config.ts
Apps
Packages
Tools
Should fix the vite issues when deployed to Render. Made some slight changes to the knowledge graph layout to make connections easier to read. Now when you hover a node or edge, it highlights all other relevant nodes/edges. This caused hover cards not to work properly, but will troubleshoot that later, as I think this change to highlighting is more impactful.
=> ENG-0000 feat(launchpad): patch knowledge graph

apps/portal/app/routes/app+/quest+/index.tsx
Apps
Packages
Tools
Reintroduces the QuestSetCards which accidentally got deleted in points rework.
=> ENG-0000 fix(portal): add quest set cards back to quest route

apps/launchpad/vite.config.ts
Apps
Packages
Tools
- Minimizes the `vite.config.ts` changes to work with the knowledge graph component.
- Builds locally (previously wasn't building) and is able to be served and run without issue via `pnpm start` from the `build` output in `launchpad` -- should be good now upon merge and redeployment.
This screenshot is accessed via the build output, not the dev server, so should mimic the Render deployment environment:
=> ENG-5345 feat(launchpad): troubleshoot knowledge graph build issue

apps/launchpad/app/components/AppSidebar.tsx, apps/launchpad/app/components/aggregate-iq.tsx, apps/launchpad/app/components/chart.tsx, apps/launchpad/app/components/skill-modal.tsx, apps/launchpad/app/components/skill-radar-chart.tsx, apps/launchpad/app/data/mock-rewards.ts, apps/launchpad/app/routes/_app+/rewards.tsx, apps/launchpad/app/routes/_index.tsx, apps/launchpad/app/types/rewards.ts
Apps
Packages
Tools
- Updates routing for `/` to redirect to `/dashboard` and updates `AppSidebar` to include the _Rewards_
- Adds `/rewards` route and brings in v0 scaffolding -- iterated on this in v0 and then moved into Launchpad after tweaking things there
- Adds in points data structure and mock data that is then passed into the `<AggregateIQ/>`  and `<SkillRadarChart/>` components
- Adds a tooltip on hover that shows point breakdown for each section of the radar chart
- On clicking the skill name, opens the 'rewards' modal that shows progress (still tweaking this modal a bit to make more reusable)
- _View All Skills_ button is a placeholder -- will add routing and detail pages for those after the preferences work
- Aims for a mid-fi implementation -- pulls in some elements from …
=> ENG-5353 ENG-5362 feat(launchpad): v0 scaffolding rewards route and mid-fi implementation

packages/graphql/package.json, packages/graphql/src/client.ts, packages/graphql/src/constants.ts
Apps
Packages
Tools
- Updates the exported `API_URL_DEV` in `constants.ts` to use the new deployment URL
- Switches the default URL for the client as `API_URL_PROD` -- this is what it's been since Dev and Prod were the same URL
- Consumers can leverage the `configureClient` approach to override / set to `API_URL_DEV` in the consuming application: https://tech.docs.intuition.systems/dev/graphql-onboarding (the process is the same, but this page will be updated to note that the Dev/Prod URLs are now different)
=> ENG-5376 feat(graphql): update constants.ts with new testnet deployment url

packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/src/client.ts, packages/graphql/src/constants.ts, pnpm-lock.yaml
Apps
Packages
Tools
- We had some drift where the most recent changes from the GraphQL package on `main` weren't brought in
- This brings these updates in. Most notably the `codegen.ts` process and the `constants.ts` with the updated API URLs. 
- Tested the `configureClient` in Launchpad after this change and it works -- the `getStats` query returned two different sets of results based on the configured override.
=> ENG-5457 feat(graphql): package parity with main

apps/launchpad/app/components/layouts/app-shell.tsx, apps/launchpad/app/components/stats-bar.tsx, apps/launchpad/app/lib/hooks/useGoBack.tsx, apps/launchpad/app/routes/_app+/minigames+/game-1.tsx, packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
Apps
Packages
Tools
- Adds in the minigame routing and layout (we can adjust the routing)
- Adds a `StatsBar` and includes this in the `AppShell` -- the data is the same query used in `ChapterProgress`
- Builds initial layout for the detail page with the following notes: query is in, but need to calculate TVL and also update the `AggregatedMetrics` to have optional precision so we can adjust these values on the fly / based on context
- Will return to these issues after rounding out other pages
=> ENG-5432 ENG-5466 feat(launchpad): detail page routing layout and appshell update with statsbar

apps/launchpad/app/components/share-modal.tsx, apps/launchpad/app/lib/state/store.ts, apps/launchpad/app/routes/_app+/minigames+/game-1.tsx, apps/launchpad/package.json, pnpm-lock.yaml
Apps
Packages
Tools
- Adds the state and flow for the share modal from the details page (no link to this yet in app, but it's `/minigames/game-1`
- Automatically copies the link upon opening modal and shows it on hover
- Made slight modifications to see if we want to make the query support user perspective, but now planning for global list
- Scaffolds out the share to Twitter/Farcaster buttons (we'll need the copy)
- Modal takes in the title and tvl and optional props to match the Figma
- Will update the modal UI as we lock it in
=> ENG-5428 ENG-5429 feat(launchpad): sharing modal flow

apps/launchpad/app/components/layouts/app-shell-context.tsx, apps/launchpad/app/components/layouts/app-shell.tsx, apps/launchpad/app/components/layouts/types.ts, apps/launchpad/app/components/minigame-card.tsx, apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx, apps/launchpad/app/components/ui/table/columns.tsx, apps/launchpad/app/components/ui/table/data-table-column-header.tsx, apps/launchpad/app/components/ui/table/data-table-pagination.tsx, apps/launchpad/app/components/ui/table/data-table-row-actions.tsx, apps/launchpad/app/components/ui/table/data-table-toolbar.tsx, apps/launchpad/app/components/ui/table/data-table-view-options.tsx, apps/launchpad/app/components/ui/table/data-table.tsx, apps/launchpad/app/routes/_app+/minigames+/game-1.tsx, apps/launchpad/package.json, pnpm-lock.yaml
Apps
Packages
Tools
- Brings in `@tanstack/react-table` and connects to the game-1 wallet list data. Adds a lot of sorting functionality, and ensures that the values are based on the list. A lot of powerful scaffolding is added with this, but we'll need to enhance the composability a bit to allow for more adjustable columns. We'll do this as an enhancement as this scaffolding gives us the power of React Table with our 1ui components.
- Updates the `AggregatedMetrics` component logic to calculate users and tvl
- Adds CTAs to Play Again and View List
- Adds invalidation so the table automatically updates after users complete the survey game
=> ENG-5433 ENG-5473 feat(launchpad): tcr table list with results, adds ctas to each page

apps/launchpad/app/components/atom-details-card.tsx, apps/launchpad/app/components/atom-details-modal.tsx, apps/launchpad/app/components/ui/table/columns.tsx, apps/launchpad/app/components/ui/table/data-table.tsx, apps/launchpad/app/lib/state/store.ts, apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
Apps
Packages
Tools
- Adds in a basic AtomDetailCard that shows in a modal upon clicking the table row
- We can always add additional information to this modal, but this adds in the basic pattern/state/UI and data passing from table row to modal
=> ENG-5463 feat(launchpad): detail modal table row click

apps/launchpad/app/routes/_app+/minigames+/game-1.tsx, apps/launchpad/app/routes/_app+/network.tsx, packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx, packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
Apps
Packages
Tools
* Allows optional precision prop in AggregatedMetrics component.
* Still takes into account formatted values (i.e. 1.25k) and forces the 2 precision
* ETH values should have precision set otherwise could render all 18 decimals
* Whole numbers will render without .00 that was previously a problem
=> ENG-5478 feat(launchpad,1ui): adjust the aggregatedmetrics component to allow optional precision

apps/launchpad/app/components/minigame-card-wrapper.tsx, apps/launchpad/app/components/minigame-card.tsx, apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx, apps/launchpad/app/components/onboarding-modal/reward-step.tsx, apps/launchpad/app/lib/hooks/usePoints.ts, apps/launchpad/app/routes/actions+/reward-points.ts, apps/launchpad/app/routes/resources+/get-points.ts, apps/launchpad/package.json, pnpm-lock.yaml
Apps
Packages
Tools
- Adds in server actions / resources for setting and getting points
- Adds in the awarding of points on success for first time completing minigame one
- Creates a usePoints hook to query the points from the resource route and display in the minigame card
=> ENG-5469 feat(launchpad): wire up points to home page and success handler

apps/launchpad/app/root.tsx
Apps
Packages
Tools
Removes any mention of Explorer and replaces it with Launchpad.
=> ENG-5492 fix(launchpad): update metadata to remove intuition explorer label

apps/launchpad/app/components/auth-cover.tsx, apps/launchpad/app/components/layouts/app-shell.tsx, apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx, apps/launchpad/app/components/onboarding-modal/topics-step.tsx, apps/launchpad/app/lib/hooks/usePoints.ts, apps/launchpad/app/lib/utils/constants.ts, apps/launchpad/app/routes/_app+/quests+/index.tsx, apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx, apps/launchpad/app/styles/globals.css
Apps
Packages
Tools
- Adds query to more pages and changes the CTAs based on state
- Modifies the results page to be based on state of completion
- Refines other loading states and general states in flow
- Pulls quest data into a constants file and makes more reusable
=> ENG-5556 feat(launchpad): ux second pass

apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx, apps/launchpad/app/lib/hooks/useQuestionData.ts, apps/launchpad/app/lib/providers/index.tsx, apps/launchpad/app/root.tsx, apps/launchpad/app/routes/_app+/dashboard.tsx, apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
Apps
Packages
Tools
- Changes the `API_URL` used in `configureClient` to be environment based
- Ensures that we're using `getSpecialPredicate` throughout, and that it respects current environment
- Also closes ENG-5583
=> ENG-5565 feat(launchpad): manage api url providers environment

apps/launchpad/app/.client/privy-logout.tsx, apps/launchpad/app/.server/auth.ts, apps/launchpad/app/components/onboarding-modal/signal-step.tsx, apps/launchpad/app/lib/utils/misc.tsx, apps/launchpad/app/routes/_app.tsx, apps/launchpad/app/routes/actions+/logout.tsx
Apps
Packages
Tools
Handles Privy session based on if the client has connected a wallet. If there is no wallet connected, it will force a logout of Privy.
=> ENG-5587 feat(launchpad): logout privy if no wallet connected

apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
Apps
Packages
Tools
Prevents survey modal from automatically closing and redirecting, handles redirect on Finish click.
=> ENG-5588 fix(launchpad): keep the modal open until they close it

apps/launchpad/app/components/atom-details-card.tsx, apps/launchpad/app/components/atom-details-modal.tsx, apps/launchpad/app/consts/general.ts
Apps
Packages
Tools
Adds a button that links to Portal to view the details of the triple/atom associated with the list item. Links to readonly route. 
=> ENG-5589 feat(launchpad): link to portal in atom details modal

apps/launchpad/app/components/atom-forms/forms/deposit-form.tsx, apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx, apps/launchpad/app/components/atom-forms/types.ts, apps/launchpad/app/components/onboarding-modal/create-step.tsx
Apps
Packages
Tools
Validation errors weren't rendering on the create step, specifically if a user had insufficient funds. Moved the check outside of the zod schema. Should revisit to figure out ideal pattern, just wanted to get this in to move QA forward.
=> ENG-5594 fix(launchpad): fix validation errors in create step

apps/launchpad/app/components/account-button.tsx
Apps
Packages
Tools
- Small QoL change from QA that removes the unused links from the account dropdown when a user is connected. We can always add these back in. Leaves in `Disconnect` since it has a specific purpose.
=> ENG-5614 feat(launchpad): streamline account dropdown menu

apps/launchpad/app/components/app-sidebar.tsx, apps/launchpad/app/components/minigame-card-wrapper.tsx, apps/launchpad/app/components/minigame-card.tsx, apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx, apps/launchpad/app/routes/_index.tsx
Apps
Packages
Tools
- Addresses feedback and closes ENG-5621, ENG-5618, ENG-5616, ENG-5649, and ENG-5651
- Summary: Streamlines the AppSidebar, changes the card CTA and adds in the See Results button, changes the app entry point, changes some copy, and tightens up the results page header
=> ENG-5644 feat(launchpad): qa pass for questions, sidebar, ctas, and other items

apps/launchpad/app/components/app-sidebar.tsx, apps/launchpad/app/lib/utils/constants.ts
Apps
Packages
Tools
- Minor changes in response to QA feedback: indent on `AppSidebar`, `/quests` route copy.
=> ENG-5675 feat(launchpad): qa pass fixes

apps/launchpad/app/components/atom-forms/forms/thing-form.tsx
Apps
Packages
Tools
Temporarily hides image upload from create form until upload issue is resolved.
=> ENG-5678 fix(launchpad): hide image upload from create form temporarily

apps/launchpad/app/components/app-sidebar.tsx
Apps
Packages
Tools
- Temporarily removes the network page until we lock in some of the data questions
- We can decide if we want to merge this in and remove or hold off -- can quickly add back in once things are locked
=> ENG-5682 feat(launchpad): temporarily removes network page

apps/portal/app/lib/graphql/client.ts, apps/portal/app/lib/services/points.ts, apps/portal/app/routes/app+/profile+/_index+/_layout.tsx, apps/portal/app/routes/app+/quest+/index.tsx, apps/portal/package.json, packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/schema.graphql, packages/graphql/src/generated/index.ts, pnpm-lock.yaml
Apps
Packages
Tools
Updates Relic points to use the new points API. This also adds support for other points using the new points API but I did not swap those out. Had to update the graphql schema to fix codegen build errors (thanks @jonathanprozzi).
=> ENG-5698 chore(portal,graphql): update relic points to use new points api

apps/launchpad/app/components/survey-modal/create-step.tsx, apps/launchpad/app/components/survey-modal/survey-modal.tsx, apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
Apps
Packages
Tools
Improves UX by carrying over the search term from the Topics step to prefill the name field in the Create step when no matching atom is found. This creates a more seamless experience for users who want to create an atom based on their search.
Changes:
- Added `initialName` prop to CreateStep component
- Modified SurveyFormContainer defaultValues to use search term
- Passed searchTerm from parent OnboardingModal component
Testing:
1. Search for a non-existent atom in Topics step
2. Click "Create" button
3. Verify name field is prefilled with search term
=> ENG-5821 feat(launchpad): prefill atom name from search term

packages/1ui/src/components/Button/Button.tsx, packages/1ui/src/components/Claim/Claim.tsx, packages/1ui/src/components/Copy/Copy.tsx, packages/1ui/src/components/Icon/Icon.tsx
Apps
Packages
Tools
- Cherrypicks this from the work I was doing to support Next inside (and outside) of the monorepo when using `1ui` -- needed to add in `'use client'` for certain components in it. Moved to a separate PR so to not include in the other ones
=> ENG-5829 feat(1ui): updates 1ui components with use client where needed
