0xIntuition/intuition-ts

apps/portal/app/components/follow/follow-modal.tsx

Apps
Packages
Tools
Follow Modal was still trying to use useCreateConfig, but should have been using useCreateClaimConfig.

ENG-0000 fix(portal): fix create config error

---

apps/portal/package.json
pnpm-lock.yaml

Apps
Packages
Tools
- Somehow this was lost in the rebase. Adds this back in -- should fix build issues.

ENG-0000 fix(portal): re-add graphql package portal

---

packages/graphql/src/queries/atoms.graphql
packages/graphql/src/queries/lists.graphql
packages/graphql/src/queries/triples.graphql

Apps
Packages
Tools
- Updates the atoms, lists, and triples queries to use aggregate versions of atoms and triples
- Runs codegen

ENG-0000 feat(graphql): updates the atoms, lists, and triples queries to use aggregates

---

apps/template/app/routes/app+/playground-hydration-search.tsx
apps/template/app/routes/app+/playground-hydration.tsx
apps/template/app/routes/app+/playground.tsx
packages/graphql/src/generated/index.ts

Apps
Packages
Tools
- Re-runs codegen to get new hooks and fixes build issue in template playground

ENG-0000 feat(graphql,template): re-runs codegen to get new hooks and fixes build issue in template playground

---

apps/portal/app/components/list/tags.tsx

Apps
Packages
Tools
Changes the headers in ListHeader on the List Detail route from Tag -> Identity and TVL -> Claim TVL

ENG-4719 fix(portal): change list headers on list detail to identity and claim tvl

---

apps/portal/app/routes/app+/explore+/_index+/lists.tsx

Apps
Packages
Tools
Adds the Featured Lists carousel to the top of the Explore Lists route.

ENG-3894 feat(portal): add featured lists to explore lists route

---

apps/portal/app/components/lists/add-identities.tsx
apps/portal/app/components/stake/stake-modal.tsx
apps/portal/app/components/tags/add-tags.tsx
apps/portal/app/lib/hooks/useCheckClaim.tsx
apps/portal/app/lib/hooks/useInvalidItems.tsx

Apps
Packages
Tools
- Swapped out fetchers for claim checker hook
- Update useInvalidItems to work with claim checker hook

ENG-4666 feat(portal): update queries in add tags modal

---

apps/portal/app/components/save-list/save-button.tsx
apps/portal/app/components/save-list/save-form.tsx
apps/portal/app/components/save-list/save-list-modal.tsx
apps/portal/app/components/save-list/save-review.tsx
apps/portal/app/components/save-list/unsave-button.tsx
apps/portal/app/components/tags/add-tags.tsx
apps/portal/app/lib/hooks/mutations/useSaveListMutation.tsx
apps/portal/app/lib/hooks/useCheckClaim.tsx
apps/portal/app/lib/hooks/useInvalidItems.tsx
apps/portal/app/routes/app+/claim+/$id.tsx

Apps
Packages
Tools
- Swaps out fetchers for queries in Save List modal
- Updates Add Tags modal to work within the Save List modal
- Created useSaveListMutation hook to handle staking on lists
- Fixed issue with Staking Modal that popped up while testing redeems

ENG-4665 feat(portal): update queries in save list modal

---

apps/portal/app/routes/app+/profile+/$wallet.tsx

Apps
Packages
Tools
- Incremental adoption of GraphQL for the metadata (left panel) when viewing another user's profile
- Certain modals are being reworked on other branches and will be updated in another PR
- We'll do another pass for the data (and continue removing unused calls) as we incrementally progress

ENG-4770 feat(portal): user metadata left panel

---

apps/portal/app/routes/app+/profile+/$wallet+/data-about.tsx

Apps
Packages
Tools
Updates User Data About route to use GraphQL query.

ENG-4760 feat(portal): user data about

---

apps/portal/app/components/list/follow.tsx
apps/portal/app/routes/app+/profile+/$wallet+/index.tsx
apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
apps/portal/app/routes/app+/profile+/_index+/index.tsx

Apps
Packages
Tools
- Replaces Legacy API data with GraphQL.

ENG-4759 feat(portal): user overview

---

apps/portal/app/.server/auth.ts
apps/portal/app/.server/privy.ts
apps/portal/app/routes/_index.tsx
apps/portal/app/routes/intro+/index.tsx

Apps
Packages
Tools
- Updates the Privy redirect logic to avoid early return `null`

ENG-0000 fix(portal): updates privy redirect logic

---

apps/data-populator/app/lib/utils/proofread.ts

eng-4966-data-populator-try-new-regexp

---

apps/portal/app/routes/app+/profile+/$wallet+/data-created.tsx

Apps
Packages
Tools
Replaces legacy API with GraphQL queries on user data created route.

ENG-4761 feat(portal): update user data created to graphql

---

apps/portal/app/routes/readonly+/profile+/$wallet+/data-about.tsx
apps/portal/app/routes/readonly+/profile+/$wallet+/index.tsx
apps/portal/app/routes/readonly+/profile+/$wallet.tsx

Apps
Packages
Tools
Updates the read only profile route to use GraphQL.
NOTE: Marking as Do Not Merge until i7n issues are resolved and we can properly test. Also need to update Data Created and Lists portion once @jonathanprozzi finishes up those on the normal app route.

ENG-4944 feat(portal): convert profile read only route to use graphql

---

apps/portal/app/components/lists/featured-lists-carousel.tsx
apps/portal/app/lib/services/lists.ts
apps/portal/app/routes/app+/home.tsx
packages/graphql/src/generated/index.ts

Apps
Packages
Tools
Replaces legacy query with GraphQL on the featured lists carousel on home.

ENG-5029 feat(portal): lists carousel

---

apps/portal/app/components/detail-info-card.tsx
apps/portal/app/components/list/tags.tsx
apps/portal/app/components/lists/add-identities-list-form.tsx
apps/portal/app/components/lists/add-identities-list-modal.tsx
apps/portal/app/components/lists/add-identities.tsx
apps/portal/app/components/save-list/save-form.tsx
apps/portal/app/components/save-list/save-list-modal.tsx
apps/portal/app/components/save-list/save-review.tsx
apps/portal/app/components/tags/add-tags.tsx
apps/portal/app/lib/state/store.ts
apps/portal/app/lib/utils/misc.tsx
apps/portal/app/routes/app+/identity+/$id.tsx
apps/portal/app/routes/app+/list+/$id+/index.tsx
apps/portal/app/routes/app+/list+/$id.tsx
apps/portal/app/routes/app+/profile+/$wallet.tsx
apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
apps/portal/app/routes/app+/quest+/chapter+/1-6-always_true.tsx
apps/portal/app/routes/readonly+/identity+/$id.tsx
apps/portal/app/routes/readonly+/list+/$id+/index.tsx
apps/portal/app/routes/readonly+/list+/$id.tsx
apps/portal/app/routes/readonly+/profile+/$wallet.tsx
packages/1ui/src/components/IdentityRow/IdentityRow.tsx
packages/graphql/src/fragments/triple.graphql
packages/graphql/src/generated/index.ts
packages/graphql/src/queries/lists.graphql
packages/graphql/src/queries/triples.graphql

Apps
Packages
Tools
Updates List Detail and List Detail readonly to use GraphQL

ENG-5015 feat(portal,graphql): lists detail

---

apps/portal/app/routes/app+/list+/$id.tsx

Apps
Packages
Tools
Added dehydratedState to the loader on List details, last commit never got pushed into previous PR which added this.

ENG-0000 fix(portal): add dehydrated state to list detail

---

apps/portal/app/components/follow/follow-modal.tsx
apps/portal/app/components/save-list/save-list-modal.tsx
apps/portal/app/components/stake/stake-actions.tsx
apps/portal/app/components/stake/stake-form.tsx
apps/portal/app/consts/general.ts

Apps
Packages
Tools
Updated the min_deposit const to match new value in production. Made sure to prioritize the min_deposit being returned from vaultDetails in all cases, particularly when the staking action rely on the radio buttons.

ENG-5146 fix(portal): audit fee fetching and calculations and fix

---

apps/portal/app/routes/app+/profile+/$wallet.tsx
apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
apps/portal/app/routes/app+/quest+/index.tsx

ENG-5259 fix(portal): fix relic point import paths

---

packages/protocol/README.md
packages/protocol/package.json
packages/protocol/src/deployments.ts
packages/protocol/src/multivault.ts
packages/protocol/tests/multivault.test.ts
packages/protocol/tsup.config.ts
pnpm-lock.yaml

Apps
Packages
Tools
* Add versioning in-line with the graphql package.
* Add tsup for building.

ENG-5377 feat(protocol): Add protocol package versioning

---

packages/protocol/README.md
packages/protocol/package.json
pnpm-lock.yaml

Apps
Packages
Tools
- Fixes example code in the readme for `protocol`
- Viem upgrade

ENG-0000 fix(protocol): readme example and upgrade viem dep

---

apps/launchpad/app/components/app-sidebar.tsx
apps/launchpad/app/components/share-modal.tsx
apps/launchpad/app/components/stats-bar.tsx

Apps
Packages
Tools
- Adds the query and list of wallets to the share modal
- Updates the side nav and removes route not in use
- Updates the side nav links
- Updates the stats bar

ENG-5470 ENG-5459 feat(launchpad): add list sharing modal, update navbar and stats bar

---

apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
apps/launchpad/app/components/atom-forms/survey-form-container.tsx
apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
apps/launchpad/app/components/onboarding-modal/signal-step.tsx
apps/launchpad/app/components/onboarding-modal/signal-toast.tsx
apps/launchpad/app/components/onboarding-modal/topics-step.tsx
apps/launchpad/app/components/onboarding-modal/types.ts

Apps
Packages
Tools
Adds links and tightens up the the survey flow

ENG-5494 feat(launchpad): add tooltiplink to docs on staking flow

---

apps/launchpad/app/routes/resources+/get-points.ts

Apps
Packages
Tools
- Fixes build/deploy issue due to incorrect `error` imported in `get-points.ts`
- Builds locally, will resolve issue on Render

ENG-5514 fix(launchpad): fix build deploy issue

---

apps/launchpad/app/components/atom-forms/form-fields/image-upload.tsx
apps/launchpad/app/components/atom-forms/forms/deposit-form.tsx
apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
apps/launchpad/app/components/create-atom-modal.tsx
apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
apps/launchpad/app/components/layouts/app-shell.tsx
apps/launchpad/app/components/onboarding-modal/create-step.tsx
apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
apps/launchpad/app/components/onboarding-modal/signal-step.tsx
apps/launchpad/app/routes/_app+/network.tsx
apps/launchpad/app/routes/actions+/reward-points.ts

Apps
Packages
Tools
- Quick pass to remove console logs
- Removes the StatsBar (from layout) and ChapterProgress (from network page
- More coming in subsequent PRs

ENG-5550 feat(launchpad): initial cleanup pass

---

apps/launchpad/app/components/atom-details-card.tsx
apps/launchpad/app/components/atom-details-modal.tsx
apps/launchpad/app/components/ui/table/columns.tsx

Apps
Packages
Tools
Removes the staking functionality from the question results. Polished the atom card/modal that opens when clicking on the rows.

ENG-5477 feat(launchpad): remove staking from question results and some polish

---

apps/launchpad/app/.server/multivault.ts
apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
apps/launchpad/app/components/onboarding-modal/reward-step.tsx
apps/launchpad/app/components/onboarding-modal/signal-step.tsx
apps/launchpad/app/consts/general.ts
apps/launchpad/app/lib/hooks/useGetMultiVaultConfig.tsx
apps/launchpad/app/routes/_app.tsx
apps/launchpad/app/routes/actions+/reward-points.ts
apps/launchpad/app/routes/resources+/get-vault-config.tsx
apps/launchpad/app/types/vault.ts

Apps
Packages
Tools
Lifts multivault config fetcher up into app route for easier access to the config throughout the app.

ENG-5521 feat(launchpad): optimize prefetching strategy

---

apps/launchpad/app/components/onboarding-modal/signal-step.tsx
apps/launchpad/app/components/submit-button.tsx

Apps
Packages
Tools
Adds SubmitButton which performs a network check before allowing user to submit a transaction. 

ENG-5566 feat(launchpad): manage chain switching

---

apps/launchpad/app/components/minigame-card-wrapper.tsx
apps/launchpad/app/components/onboarding-modal/topics-step.tsx
apps/launchpad/app/lib/graphql/client.ts
apps/launchpad/app/lib/graphql/types.ts
apps/launchpad/app/lib/hooks/useQuestionData.ts
apps/launchpad/app/routes/_app+/dashboard.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
apps/launchpad/app/routes/resources+/get-points.ts
apps/launchpad/app/routes/resources+/get-questions.$id.ts
apps/launchpad/app/routes/resources+/get-questions.ts

Apps
Packages
Tools
- Adds the query for the questions metadata
- Adds in resource route for this
- Updates hardcoded components to use this, and adds a `useQuestionData` hook

ENG-5574 feat(launchpad): wire up questions graphql query

---

apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
apps/launchpad/app/components/submit-button.tsx

Apps
Packages
Tools
Fixes atom creation error, added network handling

ENG-5590 fix(launchpad): atom creation fails

---

apps/launchpad/app/components/app-sidebar.tsx

Apps
Packages
Tools
- Changes the icon field to leverage our Icon in 1ui and updates the links and icons for the external links in AppSidebar

ENG-5611 feat(launchpad): change icon field structure and update external links in app sidebar

---

apps/launchpad/app/components/account-button.tsx
apps/launchpad/app/components/app-sidebar.tsx
apps/launchpad/app/components/minigame-card-wrapper.tsx
apps/launchpad/app/components/minigame-card.tsx
apps/launchpad/app/components/ui/table/columns.tsx
apps/launchpad/app/components/ui/table/data-table-pagination.tsx
apps/launchpad/app/components/ui/table/data-table.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
apps/launchpad/app/routes/_index.tsx
packages/graphql/codegen.ts
packages/graphql/schema.graphql
packages/graphql/src/generated/index.ts

Apps
Packages
Tools
- Catches up the 'main' `feature/launchpad` branch with `feature/launchpad-dev` -- we need the GraphQL changes so that `feature/launchpad` builds, among other reasons

ENG-0000 feat(repo): merge feature/launchpad-dev into feature/launchpad

---

apps/launchpad/app/components/activity-feed.tsx
apps/launchpad/app/routes/_app+/network.tsx

Apps
Packages
Tools
- Updates network page from QA feedback

ENG-5676 feat(launchpad): critical qa pass

---

apps/launchpad/app/components/survey-modal/survey-modal.tsx

Apps
Packages
Tools
Adds robust error handling and state validation to the survey modal's transition system to prevent crashes from race conditions during step transitions. The changes ensure graceful recovery when state becomes null during async operations.
Key Changes:
- Added state validation and fallback to INITIAL_STATE in transition handler
- Implemented error handling in transition process to prevent crashes
- Added render safeguards against null state conditions
- Added validation in onCreationSuccess callback
- Added comprehensive logging for debugging future issues
Bug Fix:
- Fixes issue where modal would crash after atom creation when transitioning to signal step
- Prevents null state errors during rapid state transitions
- Maintains modal state integrity during async …

ENG-5813 fix(launchpad): prevent race conditions in survey modal transitions

---

apps/launchpad/app/components/app-sidebar.tsx
apps/launchpad/app/components/layouts/app-shell-context.tsx
apps/launchpad/app/components/lore/chapter-header.tsx
apps/launchpad/app/components/lore/chapter-navigation.tsx
apps/launchpad/app/components/ui/table/data-table-pagination.tsx
apps/launchpad/app/components/ui/table/data-table.tsx
apps/launchpad/app/routes/_app+/lore+/$chapterId.tsx
apps/launchpad/app/routes/_app+/lore+/index.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
packages/graphql/src/generated/index.ts
packages/graphql/src/queries/lists.graphql

Apps
Packages
Tools
- Fixes spacing issues on Lore page(s)
- Fixes pagination on question results page

ENG-5844 fix(launchpad,graphql): qa fixes, pagination on results

---

apps/launchpad/app/components/share-modal.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
apps/launchpad/app/types/list-details.ts

ENG-0000 fix(launchpad): fix build error

---

apps/launchpad/app/consts/general.ts
apps/launchpad/app/root.tsx
apps/launchpad/app/routes/_app+/rewards.tsx

Apps
Packages
Tools
- Reverts some of the changes we made for the testing launch
- We can hold off on this until after we have all other changes into dev @Vitalsine85 -- mainly wanted to get this ready to go and will add to it if there's any other items I missed

ENG-5791 feat(launchpad): add environment handling back

---

apps/launchpad/app/components/chapter-progress.tsx
apps/launchpad/app/components/lore/chapter-card.tsx
apps/launchpad/app/components/ui/table/data-table.tsx
apps/launchpad/app/lib/consts/chapters.ts
apps/launchpad/app/lib/services/epochs.ts
apps/launchpad/app/lib/services/points.ts
apps/launchpad/app/lib/services/questions.ts
apps/launchpad/app/routes/_app+/dashboard.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
apps/launchpad/app/routes/resources+/get-epoch.ts
apps/launchpad/app/routes/resources+/get-question-completion.ts
apps/launchpad/app/styles/globals.css

ENG-5911 fix(launchpad): qa and enhancements (smoke test checkpoint)

---

apps/launchpad/app/components/quest-row.tsx
apps/launchpad/app/components/question-card-wrapper.tsx
apps/launchpad/app/components/survey-modal/reward-step.tsx
apps/launchpad/app/components/survey-modal/survey-modal.tsx
apps/launchpad/app/components/survey-modal/topics-step.tsx
apps/launchpad/app/routes/_app+/lore+/index.tsx
apps/launchpad/app/routes/_app+/quests+/index.tsx
apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
apps/launchpad/app/routes/actions+/reward-question-points.ts

ENG-5976 fix(launchpad): bugfixes and enhancements

---

apps/launchpad/app/components/epoch-accordion.tsx
apps/launchpad/app/components/signal-modal/signal-step.tsx
apps/launchpad/app/components/survey-modal/reward-step.tsx
apps/launchpad/app/components/survey-modal/signal-step.tsx

ENG-0000 (feat): implement ability to manually enter number of votes & other fixes

---

apps/launchpad/app/components/activity-feed-portal.tsx
apps/launchpad/app/lib/graphql/generated/index.ts
apps/launchpad/app/lib/graphql/queries/signals.graphql
apps/launchpad/app/routes/_app+/network.tsx

Apps
Packages
Tools
- Optimize signals query on Network route to reduce overfetching

ENG-0000 fix(launchpad): optimize network activity query

---

apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx

Apps
Packages
Tools
* Fix View Ecosystem Map responsiveness

ENG-0000 fix(launchpad): Fix View Ecosystem Map responsiveness

---

apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/index.tsx
apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx

ENG-6547 chore(launchpad): Update ecosystems SEO

---

apps/launchpad/app/components/ecosystem-question-card/question-row-wrapper.tsx

Apps
Packages
Tools
Add number of users to question row

ENG-6559 fix(launchpad): Add number of users to question row

---

apps/launchpad/app/.server/env.ts
apps/launchpad/app/.server/turnstile.ts
apps/launchpad/app/components/ecosystem-modal/signal-step.tsx
apps/launchpad/app/components/survey-modal/signal-step.tsx
apps/launchpad/app/components/turnstile-field.tsx
apps/launchpad/app/components/turnstile-widget.tsx
apps/launchpad/app/root.tsx
apps/launchpad/app/routes/actions+/verify-captcha.ts
apps/launchpad/app/routes/turnstile-test.tsx

ENG-0000 feat(launchpad): Add cloudflare turnstile to ecosystem / survey modals
